id: I2B3B0942
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:39:28+00:00'
last_modified: '2022-06-08T09:16:05.272373+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12070
  title: ཡིག་བསྐུར་རྣམ་གཞག་མེ་ཏོག་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '0423':
      image_group_id: I1KG12074
      title: ''
      total_pages: 370
      order: 1
      base_file: 0423.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
